CREATE TABLE place (
    ville VARCHAR(30) NOT NULL,
    quartier VARCHAR(30) NOT NULL,
    prixM2 VARCHAR(30) NOT NULL
)ENGINE=InnoDB;

INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '19393');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '10393');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '6074');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '23204');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '5276');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '5493');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '21947');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '6064');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '6447');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '16514');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '16712');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '16490');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '10261');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '6616');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '24545');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '20454');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '18980');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '22709');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '18512');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '13796');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '19036');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '13824');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '21405');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '7364');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '6898');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '5614');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '8182');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '7306');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '9230');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '12129');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '8986');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '20194');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '13237');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '7552');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '16904');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '19402');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '13458');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '21797');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '21543');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '9600');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '9048');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '10817');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '17209');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '8585');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '13504');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '17065');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '21132');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '5307');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '23249');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '5287');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '5588');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '10410');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '8717');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '16954');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '19478');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '8476');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '7701');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '9391');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '7673');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '13228');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '13182');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '10348');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Moderne', '22492');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '16452');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '6887');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '12130');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '10336');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '8565');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '24997');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '14169');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '16102');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Commercial', '21842');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '24021');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '8257');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '13962');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '22383');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Commercial', '11977');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '20184');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '13951');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '5621');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '5759');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '6826');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '11052');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '15409');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '24538');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '22005');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '7559');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '12083');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '9427');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '16133');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '19379');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '17500');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '21638');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '18670');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '22207');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '14269');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '10303');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '9965');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '5126');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '12643');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '22781');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '20853');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '12802');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '20638');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '10695');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '5445');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '19920');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '18855');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '14462');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '19776');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '7243');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '22325');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Commercial', '9034');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '22882');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '23572');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '6233');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '8298');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '7179');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '24856');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '15052');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '18989');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '19198');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '19665');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '20799');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '7293');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '17382');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '22508');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '23306');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '9891');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '10878');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '20010');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '20635');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '9701');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '8664');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '15531');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '23483');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '12631');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '13492');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '12206');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '8410');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '21695');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '20965');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '16841');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '19848');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '7537');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '15827');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '8917');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '11002');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '15569');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '23441');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Moderne', '13203');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '15029');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '14699');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '22135');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '22940');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '7352');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '9067');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '24794');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '14364');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '10347');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '9379');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '20440');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '7673');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '8132');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '22611');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '13153');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '6005');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '12737');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '8858');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '20790');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Commercial', '13789');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '11188');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '24095');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '12105');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '16349');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '12840');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '12597');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '9596');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '15498');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '14317');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '9669');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '10807');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '14821');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '5673');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '14966');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Sud', '6217');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '12226');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '13695');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '24594');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '19368');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '9074');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '17598');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '11108');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '23944');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '10734');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '21766');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '15634');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '13378');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '20908');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '24980');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '19129');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '23238');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '11752');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '5207');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '23018');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '17285');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '10015');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '5936');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '6434');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '11834');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '5425');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '18997');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '16470');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '23110');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Historique', '9445');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '10417');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Moderne', '6155');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '12011');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '5507');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '21249');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '13021');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '14699');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '7293');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '17243');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '16815');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '11487');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '12771');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '23013');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '14779');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '16663');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '17298');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Historique', '19573');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '5919');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '10561');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '14094');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '15698');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '8411');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '19668');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '18099');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '8055');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '17240');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '14059');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '21369');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '16569');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '12255');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '15060');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '16408');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '13125');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '15407');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '18764');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '22746');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '21830');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '23105');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '21005');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '18312');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '12299');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '9917');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '15445');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '14745');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '16167');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '20125');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '9101');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '15297');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Résidentiel', '5034');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '10618');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '14940');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '6892');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '13946');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '16782');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '18016');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '9813');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '13521');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '17669');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '5686');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '20554');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '5284');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '20857');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '16777');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '22724');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '8668');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '5777');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '24343');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '13048');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '17974');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '22268');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '15198');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '18804');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '12146');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '16036');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '12628');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '8333');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '6663');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '15488');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '21908');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '19638');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '15452');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '21493');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '9729');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '6118');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '20647');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '20748');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '7846');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '18517');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '24955');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '22886');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '22335');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '21717');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '10046');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '16749');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '15798');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '13721');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '15949');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '5737');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '10179');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '17532');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '19080');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '16607');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '17663');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '13188');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '17716');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '23837');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '24782');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '6746');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '19030');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '23156');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '12708');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '19347');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '16594');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '9882');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '18414');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '22175');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Moderne', '14542');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '10429');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '15033');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '15615');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '20574');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '20374');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '20036');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '17932');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '20248');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '18163');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Industriel', '12150');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '9577');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '20419');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '6445');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '20896');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '6765');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '12868');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '11379');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '23828');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '10185');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '21361');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '24164');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '20019');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '23721');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '23255');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '11240');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '6332');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '12203');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '12696');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '18775');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '16609');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '16424');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '8430');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '15297');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '7132');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '10043');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '11938');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '12380');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '14279');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '12745');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '20090');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '5143');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '23056');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '18224');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '10566');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '10983');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '8643');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '13853');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '7944');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '5045');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '19054');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '5867');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '22204');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Industriel', '10681');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '23564');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '21505');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '17933');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '7072');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '12397');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '10461');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '16482');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '21948');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '11910');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '24120');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '5800');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '19755');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '22195');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '6598');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '17533');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '12495');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '18713');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '15540');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '5389');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '16782');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '14637');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '15075');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '5495');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '8472');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '11204');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '12374');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '11288');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '24102');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '12103');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '10815');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '17067');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '20210');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '8354');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '18543');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '14044');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '18937');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '14363');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '23144');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '18953');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '12718');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '12686');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '12959');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '14178');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '11590');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '7239');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '8623');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '20496');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '7307');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '24353');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '9264');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '20241');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '13699');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '21183');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '14270');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '23526');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '7745');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '6031');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '22525');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '15150');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '7213');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '20676');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '8516');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '15040');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '22595');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '5625');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '13124');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '18925');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '6561');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '16560');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '10214');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '12970');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '23659');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '12859');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '6851');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '12730');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '6262');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '13359');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '9253');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '9439');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '24695');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '7807');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '13297');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '16377');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '22632');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '24417');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '8125');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '8936');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '18796');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '22948');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '13595');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '21897');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '19765');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '13215');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '19027');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '24556');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '10619');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '13180');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '15575');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '22436');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '20411');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '9870');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '17991');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '14516');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '23918');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '14673');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '12176');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '24994');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '18781');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Historique', '18152');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '13017');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '22280');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '19818');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '9964');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '21842');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '6806');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Commercial', '8376');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '18596');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '21053');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '5272');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '6010');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '15929');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '11272');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '15735');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '13318');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '18409');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '13613');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '15157');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '16924');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '20772');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '24663');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '5131');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '21964');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '5096');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '16338');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '13905');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '12687');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '16087');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '21287');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '8389');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '11108');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '8019');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '18396');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '5584');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '18964');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '11064');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '6721');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '22478');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '8851');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '21207');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '5971');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '16817');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '21705');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '9095');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '23867');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '15788');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '11144');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '14917');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '6562');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '11963');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '24065');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '8102');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '23500');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '5504');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '16690');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '10661');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '21631');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '8992');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '21329');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '21380');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '21291');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '6651');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '12789');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '11464');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '22948');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '15881');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '19542');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '17779');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '17365');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '22747');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '15398');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '21443');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '22035');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '10736');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '19920');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '8728');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '6960');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '15923');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '10651');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '8791');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '22353');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '15081');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '24641');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '20284');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '22259');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '6923');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '13001');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '20132');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '6010');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '14867');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '7005');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '15008');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '23617');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '15059');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '20856');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '21050');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '19450');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '9449');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '16351');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '10613');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '5971');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '7652');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '8413');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '17337');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '20644');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '13492');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '5758');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '15260');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '17004');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '10090');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '21603');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '14792');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '10247');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '22589');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '21405');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '19010');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '7722');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '13401');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '8334');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '22748');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '9492');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '21078');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '8793');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '20895');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '24107');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '18154');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '21694');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '23110');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '11442');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '18650');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '7382');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '9367');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '19757');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '8217');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Commercial', '5983');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '18633');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '14165');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '21849');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '19258');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '10238');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '10896');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Résidentiel', '19316');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '17833');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '11791');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '23602');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '24192');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '22200');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '8451');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '24490');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '17047');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '17383');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Moderne', '18452');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '12089');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '23500');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '21164');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Résidentiel', '18880');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '8154');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '9448');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '21039');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '23648');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '8069');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '6773');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '18529');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '12294');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '19225');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '11560');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '19189');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '12804');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '15487');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Historique', '9709');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '23571');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '5194');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '5586');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '14540');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '11656');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Historique', '20052');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '23195');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '23854');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '11422');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '14321');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '13619');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '14028');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '10284');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '23336');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '20692');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '8083');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '17252');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '13976');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '13765');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '22707');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '21020');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '22907');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '24261');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Industriel', '14294');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '19957');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '5187');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '5099');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '6951');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '12313');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '16111');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '16573');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '9472');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '13440');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '14498');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '5553');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '21191');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '19046');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '8341');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '15272');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '14964');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '20063');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '16906');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '23431');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '21566');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '5652');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '5559');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '7641');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '5299');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '8344');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '13597');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '22259');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '15530');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '23100');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Industriel', '13949');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '21253');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '11228');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '16051');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '16638');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '14805');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '15845');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '9021');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '10398');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '23939');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '23958');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '18350');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '9403');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '15386');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '23581');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '23338');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '20932');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '19249');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '22435');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '9606');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '16433');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Industriel', '14999');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '24976');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '13520');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '6664');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '9369');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '18811');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '12278');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '13426');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '20220');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '13309');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '11781');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '13330');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '10915');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '15671');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '19373');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '9634');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '14929');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '22379');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '15930');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '24574');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '12633');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '24166');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '24205');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '18999');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '15895');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '11998');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Sud', '11318');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '21976');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '16141');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '22866');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '5804');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '5608');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '22644');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Résidentiel', '14744');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '10795');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '24048');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '17443');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '14485');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '22540');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '21338');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Moderne', '11483');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '19859');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '22995');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Est', '15850');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '6156');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '16814');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '16770');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '16866');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '5621');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '9320');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '13594');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '24703');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '11843');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '20733');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '22386');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '17134');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '16800');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '11590');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '20269');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '8121');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Nord', '16740');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '19973');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '18443');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '14715');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '23558');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '17238');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '18178');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '15818');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '7125');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '8813');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '19443');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Industriel', '19281');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '23913');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Nord', '13028');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '6888');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '5889');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '14397');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '22333');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Est', '17275');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '23298');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Commercial', '22516');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '13278');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Industriel', '24508');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '12617');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '20930');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '20976');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Sud', '6994');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Commercial', '14459');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '14836');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '11813');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '23692');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '7366');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '14004');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Résidentiel', '14640');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '12153');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '20954');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '9379');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Historique', '16579');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '7782');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '9130');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Centre', '16217');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Commercial', '21397');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '5117');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '16841');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Moderne', '24611');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Ouest', '16234');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '12502');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '15311');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '17910');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Commercial', '5628');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '11217');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '10142');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '15082');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '13025');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '17619');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '17889');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '10806');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '22116');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Ouest', '5367');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Sud', '18981');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '8683');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '23608');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '23674');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '11898');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '10771');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '19833');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '21346');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '5457');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Nord', '13413');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '9628');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '7887');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '9273');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '5189');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '13352');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '7783');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '24745');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Résidentiel', '12438');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '20741');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '5906');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '10747');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '8753');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '17165');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Est', '5289');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '19934');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Nord', '6786');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '6477');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '18337');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '10035');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '21835');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '21976');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Moderne', '10134');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Résidentiel', '15475');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '23890');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '20684');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '13742');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Commercial', '19360');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '18892');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Résidentiel', '18426');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Ouest', '11427');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Nord', '5421');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '13954');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '13932');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Historique', '15511');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '5462');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '18369');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Centre', '15540');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '12465');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '11868');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '11403');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '8580');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Ouest', '17710');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '19931');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '24781');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '23428');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Ouest', '24189');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '21206');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Est', '8102');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '23627');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Industriel', '24014');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '24941');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '15035');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '24087');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Ouest', '8512');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '9215');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Sud', '10874');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Nord', '13340');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Nord', '23654');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '10654');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Est', '19052');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '5719');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '16066');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Est', '7986');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Moderne', '7829');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Sud', '7686');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Centre', '8090');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '15438');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Industriel', '6953');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '22701');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Sud', '11705');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Commercial', '20748');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Commercial', '22622');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Est', '21044');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '15259');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '23492');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Moderne', '20025');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Historique', '15398');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Est', '12690');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Commercial', '22392');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Centre', '16074');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '5404');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Ouest', '10458');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Nord', '18004');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '22404');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Historique', '13145');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Industriel', '11653');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Ouest', '16613');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Sud', '24147');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Sud', '10082');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Historique', '24658');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Industriel', '6233');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Ouest', '20597');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Historique', '21812');
INSERT INTO place (ville, quartier, prixM2) VALUES ('New York', 'Résidentiel', '22720');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '21672');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Résidentiel', '18644');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Industriel', '6795');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '11431');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Centre', '9135');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '15291');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Résidentiel', '24425');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Résidentiel', '5371');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '22821');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Centre', '5004');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Sud', '17429');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Sud', '6192');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Historique', '5267');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Moderne', '7895');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Centre', '14628');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Dubai', 'Centre', '10294');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Madrid', 'Est', '22703');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Est', '8359');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Commercial', '15896');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '11895');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '12816');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '16826');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Berlin', 'Ouest', '13256');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Historique', '21927');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Sud', '8531');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Paris', 'Résidentiel', '17393');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Industriel', '17862');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Commercial', '21132');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Nord', '12697');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Industriel', '9963');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Nord', '14437');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Centre', '22708');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Rome', 'Commercial', '8961');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Centre', '13792');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '8331');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Londres', 'Moderne', '7393');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Sydney', 'Moderne', '15090');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Moscou', 'Sud', '22307');
INSERT INTO place (ville, quartier, prixM2) VALUES ('Tokyo', 'Moderne', '5109');
